# Generated by Django 3.0.7 on 2020-06-06 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posts/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user/'),
            preserve_default=False,
        ),
    ]
