# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_awardletterrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
