# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_auto_20200607_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.User')),
            ],
        ),
    ]
